services:
  app:
    container_name: url-shortener-nestjs-app
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/workspace
    ports:
      - "3000:3000"
    command: sleep infinity
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/shortener_db
      REDIS_HOST: redis
      REDIS_PORT: 6379

  postgres:
    image: postgres:15
    restart: always
    container_name: url-shortener-nestjs-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shortener_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    container_name: url-shortener-nestjs-redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
